import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { monitoringCapability } from "../src/lib/schema";

const connectionString = process.env.POSTGRES_URL;
if (!connectionString) {
  console.error("POSTGRES_URL environment variable is not set");
  process.exit(1);
}

const client = postgres(connectionString);
const db = drizzle(client);

const capabilities = [
  // ── CPU ──────────────────────────────────────────────────────────────────
  {
    capabilityKey: "linux_cpu_usage_high",
    name: "CPU Usage",
    description: "Overall CPU utilisation across all cores",
    category: "linux",
    metric: "node_cpu_usage_percent",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_cpu_usage_percent{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 80,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: '100 - avg(rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100',
  },
  {
    capabilityKey: "linux_cpu_iowait_high",
    name: "CPU I/O Wait",
    description: "Percentage of time CPUs are waiting on disk I/O",
    category: "linux",
    metric: "node_cpu_iowait_percent",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_cpu_iowait_percent{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 20,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: 'avg(rate(node_cpu_seconds_total{mode="iowait"}[2m])) * 100',
  },
  {
    capabilityKey: "linux_load1_high",
    name: "Load Average (1m)",
    description: "1-minute load average — high values indicate CPU saturation",
    category: "linux",
    metric: "node_load1",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_load1{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 4,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: "node_load1",
  },
  {
    capabilityKey: "linux_load5_high",
    name: "Load Average (5m)",
    description: "5-minute load average",
    category: "linux",
    metric: "node_load5",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_load5{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 4,
    defaultWindow: "10m",
    suggestedSeverity: "warning",
    scrapeQuery: "node_load5",
  },

  // ── Memory ────────────────────────────────────────────────────────────────
  {
    capabilityKey: "linux_memory_usage_high",
    name: "Memory Usage",
    description: "RAM utilisation percentage",
    category: "linux",
    metric: "node_memory_usage_percent",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_memory_usage_percent{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 80,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
  },
  {
    capabilityKey: "linux_swap_usage_high",
    name: "Swap Usage",
    description: "Swap space utilisation percentage",
    category: "linux",
    metric: "node_swap_usage_percent",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_swap_usage_percent{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 50,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: "(1 - node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes) * 100",
  },

  // ── Disk ─────────────────────────────────────────────────────────────────
  {
    capabilityKey: "linux_disk_usage_high",
    name: "Disk Usage",
    description: "Root filesystem utilisation percentage",
    category: "linux",
    metric: "node_filesystem_usage_percent",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_filesystem_usage_percent{instance="$machine",mountpoint="/"}[$window]) > $threshold',
    defaultThreshold: 85,
    defaultWindow: "10m",
    suggestedSeverity: "critical",
    scrapeQuery: '(1 - node_filesystem_avail_bytes{mountpoint="/",fstype!~"tmpfs|devtmpfs"} / node_filesystem_size_bytes{mountpoint="/",fstype!~"tmpfs|devtmpfs"}) * 100',
  },
  {
    capabilityKey: "linux_disk_read_throughput",
    name: "Disk Read Throughput",
    description: "Disk read throughput in bytes per second",
    category: "linux",
    metric: "node_disk_read_bytes_per_sec",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_disk_read_bytes_per_sec{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 104857600,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: 'sum(rate(node_disk_read_bytes_total{device!~"sr.*|loop.*"}[2m]))',
  },
  {
    capabilityKey: "linux_disk_write_throughput",
    name: "Disk Write Throughput",
    description: "Disk write throughput in bytes per second",
    category: "linux",
    metric: "node_disk_write_bytes_per_sec",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_disk_write_bytes_per_sec{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 104857600,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: 'sum(rate(node_disk_written_bytes_total{device!~"sr.*|loop.*"}[2m]))',
  },

  // ── Network ───────────────────────────────────────────────────────────────
  {
    capabilityKey: "linux_network_rx_high",
    name: "Network Receive Throughput",
    description: "Inbound network traffic in bytes per second",
    category: "linux",
    metric: "node_network_receive_bytes_per_sec",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_network_receive_bytes_per_sec{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 104857600,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: 'sum(rate(node_network_receive_bytes_total{device!~"lo"}[2m]))',
  },
  {
    capabilityKey: "linux_network_tx_high",
    name: "Network Transmit Throughput",
    description: "Outbound network traffic in bytes per second",
    category: "linux",
    metric: "node_network_transmit_bytes_per_sec",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_network_transmit_bytes_per_sec{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 104857600,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: 'sum(rate(node_network_transmit_bytes_total{device!~"lo"}[2m]))',
  },
  {
    capabilityKey: "linux_network_errors",
    name: "Network Errors",
    description: "Network interface error rate per second",
    category: "linux",
    metric: "node_network_errors_per_sec",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_network_errors_per_sec{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 10,
    defaultWindow: "5m",
    suggestedSeverity: "critical",
    scrapeQuery: 'sum(rate(node_network_receive_errs_total{device!~"lo"}[2m])) + sum(rate(node_network_transmit_errs_total{device!~"lo"}[2m]))',
  },

  // ── System ────────────────────────────────────────────────────────────────
  {
    capabilityKey: "linux_open_file_descriptors_high",
    name: "Open File Descriptors",
    description: "Number of open file descriptors — nearing system limits causes failures",
    category: "linux",
    metric: "node_open_file_descriptors",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_open_file_descriptors{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 65536,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: "node_filefd_allocated",
  },
  {
    capabilityKey: "linux_context_switches_high",
    name: "Context Switches",
    description: "CPU context switch rate per second — high values indicate CPU pressure",
    category: "linux",
    metric: "node_context_switches_per_sec",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_context_switches_per_sec{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 100000,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: "rate(node_context_switches_total[2m])",
  },
  {
    capabilityKey: "linux_uptime",
    name: "System Uptime",
    description: "Machine uptime in seconds — monitors unexpected reboots",
    category: "linux",
    metric: "node_uptime_seconds",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'node_uptime_seconds{instance="$machine"} < $threshold',
    defaultThreshold: 300,
    defaultWindow: "1m",
    suggestedSeverity: "critical",
    scrapeQuery: "node_time_seconds - node_boot_time_seconds",
  },

  // ── Linux extra ──────────────────────────────────────────────────────────
  {
    capabilityKey: "linux_disk_iops_high",
    name: "Disk IOPS",
    description: "Total disk I/O operations per second across all block devices",
    category: "linux",
    metric: "node_disk_iops",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_disk_iops{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 5000,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: 'sum(rate(node_disk_reads_completed_total{device!~"sr.*|loop.*"}[2m])) + sum(rate(node_disk_writes_completed_total{device!~"sr.*|loop.*"}[2m]))',
  },
  {
    capabilityKey: "linux_disk_io_utilization",
    name: "Disk I/O Utilization",
    description: "Percentage of time the busiest disk device is busy",
    category: "linux",
    metric: "node_disk_io_util_percent",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_disk_io_util_percent{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 90,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: 'max(rate(node_disk_io_time_seconds_total{device!~"sr.*|loop.*"}[2m])) * 100',
  },
  {
    capabilityKey: "linux_processes_high",
    name: "Running Processes",
    description: "Number of currently running processes — high counts indicate forks or process leaks",
    category: "linux",
    metric: "node_procs_running",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_procs_running{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 500,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: "node_procs_running",
  },
  {
    capabilityKey: "linux_zombie_processes",
    name: "Zombie Processes",
    description: "Number of zombie processes — non-zero values indicate resource leaks",
    category: "linux",
    metric: "node_procs_blocked",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_procs_blocked{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 5,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: "node_processes_state{state='Z'}",
  },
  {
    capabilityKey: "linux_tcp_connections_high",
    name: "TCP Connections",
    description: "Total established TCP connections — nearing OS limits causes connection failures",
    category: "linux",
    metric: "node_tcp_connections",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_tcp_connections{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 10000,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: 'node_sockstat_TCP_inuse',
  },
  {
    capabilityKey: "linux_memory_page_faults_high",
    name: "Memory Page Fault Rate",
    description: "Major page fault rate per second — high values indicate memory pressure with disk swapping",
    category: "linux",
    metric: "node_memory_major_page_faults_per_sec",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_memory_major_page_faults_per_sec{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 100,
    defaultWindow: "5m",
    suggestedSeverity: "critical",
    scrapeQuery: "rate(node_vmstat_pgmajfault[2m])",
  },

  // ── Network extra ─────────────────────────────────────────────────────────
  {
    capabilityKey: "linux_network_packet_drops",
    name: "Network Packet Drops",
    description: "Network packet drop rate — dropped packets indicate saturation or misconfiguration",
    category: "linux",
    metric: "node_network_drops_per_sec",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_network_drops_per_sec{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 100,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: 'sum(rate(node_network_receive_drop_total{device!~"lo"}[2m])) + sum(rate(node_network_transmit_drop_total{device!~"lo"}[2m]))',
  },
  {
    capabilityKey: "linux_network_tcp_retransmit_rate",
    name: "TCP Retransmit Rate",
    description: "TCP segment retransmission rate — high values indicate network congestion or packet loss",
    category: "linux",
    metric: "node_tcp_retransmit_per_sec",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_tcp_retransmit_per_sec{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 50,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: "rate(node_netstat_Tcp_RetransSegs[2m])",
  },
  {
    capabilityKey: "linux_network_connection_refused",
    name: "TCP Connection Resets",
    description: "TCP connection reset rate — high values indicate service crashes or firewall drops",
    category: "linux",
    metric: "node_tcp_resets_per_sec",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_tcp_resets_per_sec{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 20,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: "rate(node_netstat_Tcp_EstabResets[2m])",
  },
  {
    capabilityKey: "linux_network_conntrack_usage",
    name: "Conntrack Table Usage",
    description: "Connection tracking table utilisation — exhaustion causes new connections to fail",
    category: "linux",
    metric: "node_conntrack_usage_percent",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(node_conntrack_usage_percent{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 80,
    defaultWindow: "5m",
    suggestedSeverity: "critical",
    scrapeQuery: "(node_nf_conntrack_entries / node_nf_conntrack_entries_limit) * 100",
  },

  // ── Docker ────────────────────────────────────────────────────────────────
  {
    capabilityKey: "docker_container_cpu_high",
    name: "Container CPU Usage",
    description: "CPU utilisation for a Docker container",
    category: "linux",
    metric: "container_cpu_usage_percent",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(container_cpu_usage_percent{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 80,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: 'sum(rate(container_cpu_usage_seconds_total{image!=""}[2m])) by (name) * 100',
  },
  {
    capabilityKey: "docker_container_memory_high",
    name: "Container Memory Usage",
    description: "Memory utilisation for a Docker container as a percentage of its limit",
    category: "linux",
    metric: "container_memory_usage_percent",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(container_memory_usage_percent{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 85,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: 'container_memory_usage_bytes{image!=""} / container_spec_memory_limit_bytes{image!=""} * 100',
  },
  {
    capabilityKey: "docker_container_restart_rate",
    name: "Container Restart Rate",
    description: "Docker container restart count in the observation window — indicates crash-looping",
    category: "linux",
    metric: "container_restart_count",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'increase(container_restart_count{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 3,
    defaultWindow: "15m",
    suggestedSeverity: "critical",
    scrapeQuery: 'sum(increase(container_start_total{image!=""}[15m])) by (name)',
  },
  {
    capabilityKey: "docker_container_oom_killed",
    name: "Container OOM Kills",
    description: "Containers killed by the OOM (out-of-memory) killer",
    category: "linux",
    metric: "container_oom_events_total",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'increase(container_oom_events_total{instance="$machine"}[$window]) > $threshold',
    defaultThreshold: 0,
    defaultWindow: "5m",
    suggestedSeverity: "critical",
    scrapeQuery: 'sum(increase(container_oom_events_total{image!=""}[5m])) by (name)',
  },

  // ── Kubernetes ────────────────────────────────────────────────────────────
  {
    capabilityKey: "k8s_pod_restart_rate_high",
    name: "Pod Restart Rate",
    description: "Kubernetes pod restart count — indicates crash-looping workloads",
    category: "kubernetes",
    metric: "kube_pod_restart_count",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'increase(kube_pod_container_status_restarts_total{node="$machine"}[$window]) > $threshold',
    defaultThreshold: 5,
    defaultWindow: "15m",
    suggestedSeverity: "critical",
    scrapeQuery: 'sum(increase(kube_pod_container_status_restarts_total[15m])) by (pod, namespace)',
  },
  {
    capabilityKey: "k8s_node_cpu_high",
    name: "Node CPU Usage",
    description: "Kubernetes node CPU utilisation percentage",
    category: "kubernetes",
    metric: "kube_node_cpu_usage_percent",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(kube_node_cpu_usage_percent{node="$machine"}[$window]) > $threshold',
    defaultThreshold: 80,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: '100 - avg(rate(node_cpu_seconds_total{mode="idle"}[2m])) by (instance) * 100',
  },
  {
    capabilityKey: "k8s_node_memory_high",
    name: "Node Memory Usage",
    description: "Kubernetes node memory utilisation percentage",
    category: "kubernetes",
    metric: "kube_node_memory_usage_percent",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(kube_node_memory_usage_percent{node="$machine"}[$window]) > $threshold',
    defaultThreshold: 85,
    defaultWindow: "5m",
    suggestedSeverity: "warning",
    scrapeQuery: "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
  },
  {
    capabilityKey: "k8s_pods_not_ready",
    name: "Pods Not Ready",
    description: "Number of pods in a non-Ready state — may indicate workload degradation",
    category: "kubernetes",
    metric: "kube_pod_not_ready",
    parameters: { machine: "string", threshold: "number", window: "duration" },
    alertTemplate: 'avg_over_time(kube_pod_not_ready{node="$machine"}[$window]) > $threshold',
    defaultThreshold: 2,
    defaultWindow: "5m",
    suggestedSeverity: "critical",
    scrapeQuery: 'sum(kube_pod_status_ready{condition="false"})',
  },
];

async function seed() {
  console.log("Seeding monitoring capabilities...");

  for (const cap of capabilities) {
    await db
      .insert(monitoringCapability)
      .values(cap)
      .onConflictDoUpdate({
        target: monitoringCapability.capabilityKey,
        set: {
          name: cap.name,
          description: cap.description,
          category: cap.category,
          metric: cap.metric,
          parameters: cap.parameters,
          alertTemplate: cap.alertTemplate,
          defaultThreshold: cap.defaultThreshold,
          defaultWindow: cap.defaultWindow,
          suggestedSeverity: cap.suggestedSeverity,
          scrapeQuery: cap.scrapeQuery,
        },
      });
    console.log(`  ✓ ${cap.capabilityKey}`);
  }

  console.log("Done! Seeded", capabilities.length, "capabilities.");
  await client.end();
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
