{{- if eq (include "noblinks-agent.deployPrometheus" .) "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "noblinks-agent.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "noblinks-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "noblinks-agent.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: prometheus
  template:
    metadata:
      labels:
        {{- include "noblinks-agent.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: prometheus
    spec:
      serviceAccountName: {{ include "noblinks-agent.serviceAccountName" . }}
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --storage.tsdb.retention.time={{ .Values.prometheus.retention }}
            - --web.enable-lifecycle
            - --web.listen-address=0.0.0.0:9090
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: rules
              mountPath: /etc/prometheus/rules
            - name: storage
              mountPath: /prometheus
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "noblinks-agent.fullname" . }}-prometheus-config
        - name: rules
          configMap:
            name: {{ include "noblinks-agent.fullname" . }}-prometheus-rules
        - name: storage
          emptyDir: {}
{{- end }}
