{{- if eq (include "noblinks-agent.deployAlertmanager" .) "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "noblinks-agent.fullname" . }}-alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "noblinks-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "noblinks-agent.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: alertmanager
  template:
    metadata:
      labels:
        {{- include "noblinks-agent.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: alertmanager
    spec:
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: alertmanager
          image: "{{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}"
          imagePullPolicy: {{ .Values.alertmanager.image.pullPolicy }}
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/alertmanager
            - --web.listen-address=0.0.0.0:9093
          ports:
            - name: http
              containerPort: 9093
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
            - name: credentials
              mountPath: /etc/noblinks
              readOnly: true
            - name: storage
              mountPath: /alertmanager
          resources:
            {{- toYaml .Values.alertmanager.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "noblinks-agent.fullname" . }}-alertmanager-config
        - name: credentials
          secret:
            secretName: {{ include "noblinks-agent.fullname" . }}-credentials
            items:
              - key: agentToken
                path: agentToken
        - name: storage
          emptyDir: {}
{{- end }}
