{{- if .Values.kubeStateMetrics.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "noblinks-agent.fullname" . }}-kube-state-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "noblinks-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: kube-state-metrics
{{- end }}
